### PR TITLE
docker-compose yml

### PR DESCRIPTION
**Pull request by julienchastang**
docker-compose yml for firing up the TDS

### CODE REVIEW

**Comment by WardF** [comment]
Looks good to me; I'd recommend leaving the shell script in place as well, for those people without docker compose.

**Comment by dopplershift** [comment]
Not saying anything needs to change, but wanted to point out: the image unidata/tds-buildconfig:v4.6.4-SNAPSHOT will pull in the config.zip of TDS configuration at the time that the container is built. This would eventually eliminate the need to have a config directory mounted.

The benefits of eliminating mounts is that when you're running things on, say Azure or  AWS, using docker-machine, those mounts are to directories on those machines, not the localhost where you're running the docker commands; that forces another step to put the configuration on those machines, making the set-up of those instances more manually intensive (or at least prone to forgetting that step when you come back 6 months later).

Anyhow, file looks good!

**Comment by julienchastang** [comment]
Ward, if you want, I'll leave my remote branch on github that contains the shell script.

I do now see the power of docker-compose. I had an aha moment when I realized how potentially easy it is going to be run a multicontainer environment with ldm/ramadda/tds. There should probably be a data container in there too somewhere -- still figuring that part out. We really are getting closer to a turnkey solution (though there will always be some degree of configuration, inevitably).

In fact, we probably ought to have a directory like Unidata-Dockerfiles/compose that would contain our multicontainer docker-compose yml configuration files.

**Comment by dopplershift** [comment]
It makes more sense IMO to logically group things. For instance, one directory for the motherlode clone, that has all special dockerfiles, compose config, other config files, etc. I already have one such one for jupyterhub. You'll be surprised how dockerfiles can still end up specific to a machine, or need machine specific secret files, that you want to reference but keep out of git.

The jupyterhub dockerfiles and docker-compose.yml show how to go about creating a data container. I'd also be happy to come by and walk through it with you.

**Comment by WardF** [comment]
I'm ok with a move to docker-compose, but I think we need to either
document how to use it without compose, or provide a script, or some other
alternative.  Docker compose is still labeled not for use in production
(although it does seem pretty close), and it is not universal; it won't run
on any of my OSX boxes, for example.    It also doesn't really seem like we
need to choose one or the other, we can provide multiple ways for running
things simultaneously.

Those are my thoughts, but if we want to go straight docker compose I won't
protest.

**Comment by WardF** [comment]
I second Ryan's comment; structurally it feels better to group by
project/purpose.

**Comment by dopplershift** [comment]
@WardF I'm not passionate about it, but there's an argument to be made here that since these containers aren't "for production" either yet, we should aim for what we think the end solution will be, or what we want it to be. Also, while we don't have to pick one, but we do have to maintain everything that we pick.

Not a big deal to me either way because I'm not on the hook.

**Comment by julienchastang** [comment]
If it is OK, I am going to merge this. Feel free to iterate on what I have for improvements.

**Comment by WardF** [comment]
Nor am I, although I do think documenting how to use it outside of docker
compose might be the best way to go; if people want to take that
information and turn it into a script themselves, that would work for
myself personally and for the larger community.  Plus it encourages good
documentation which is just good practice :).

It's probable that this won't matter in practice, so however Julien
proceeds will be fine with me.

**Comment by dopplershift** [comment]
:+1:

**Comment by WardF** [comment]
Out of curiosity, @julienchastang (or @dopplershift if you've played with it); does docker-compose have any benefit/impact on containers using `x11` forwarding? It would be great if so.

**Comment by dopplershift** [comment]
None specific to X11 that I'm aware of. Chief benefits in general:
- Clean configuration file equivalent to `docker` command-line arguments
- Simplified relationships between containers (sharing volumes or network)
- Easy ability to treat multiple containers together as one application.

So unless your X11 needs multiple containers (which I didn't think it did), compose is just a simple (and standardized) bash script.

**Comment by WardF** [comment]
Ok; makes sense, it shouldn’t be more difficult (and will probably be
easier insofar as the required mappings will be contained in the compose
.yml file).

For context, enabling x11 forwarding with docker has (so far) required
jumping through a few different hoops, which vary depending on whether
you’re on OSX or linux. I’m hoping there will eventually just be a way to
toggle it on, but they aren’t there yet.
​

**Pull request merged**
