### PR TITLE
scriptified start of container

### PR DESCRIPTION
**Pull request by julienchastang**
@lesserwhirls, @WardF  Put a script infront of Docker command. I can iterate if necessary.

### CODE REVIEW

**Comment by dopplershift** [comment]
Why a script and not just a `docker-compose.yml` file? This would seem to be the def facto standard these days.

**Comment by WardF** [comment]
I'm on my phone at an appointment so can't check myself at the moment, but is docker compose broadly available now or is it still OS X only? I think having the .yml file would be great, but until compose is universal (and it may be at this point) it makes sense to provide for environments without it as well.

**Comment by dopplershift** [comment]
Docker Compose works well on both OSX and Linux. I think the misunderstanding of "mac only" comes from the fact that of those that can install the Docker Toolbox, Mac and Windows, compose only works on Mac.

docker/compose#1085 would seem to indicate that running on Windows is a non-issue now, however (it _is_ a python script after all).

**Comment by julienchastang** [comment]
According to the Docker Compose documentation “Compose is a tool for defining and running multi-container applications with Docker.” Running multiple containers is not the goal here, at least not yet. They yml facilities of DC seem attractive and may be re-purposed for single container applications, but I want command-line parameterization and the ability to define defaults. It seems like a plain-old shell script  will suffice.

**Comment by dopplershift** [comment]
Speaking from experience, Docker compose excels at single container execution. It provides a single configuration file for the execution of a container. Even if you parameterize with the shell script, you still have to remember the proper arguments to supply when you differ from the defaults. The config file lets you codify on disk the settings (directory, etc.), so that re-running the last config doesn't depend on your shell history. All I ever need to do is "docker-compose up -d". Means I don't have to think how to run each application--it's always the same.

You also gain the fact that the same tool scales running multiple containers--like a motherlode clone with LDM, TDS, and a shared data container.  All that with a tool that's simpler than writing a shell script from scratch.

**Comment by lesserwhirls** [comment]
Yeah, I agree with Ryan. Much easier to edit a .yml file that remember the
proper args, or better yet, write yet another script so you do not have to
remember the magic incantation. We will certainly be using docker compose
in out next TDS workshop (old-ass centOS willing), and that's the path we
are taking with the canonical TDS dockerfiles in the thredds repository in
git.

It seems as though docker compose is the way to go if the end game is a
Unidata in a box concept.

Sean

**Comment by julienchastang** [comment]
Ryan and Sean, since you are passionate about this, would you be willing to  do a pull request based on docker compose so we can compare the two approaches? Thanks.

**Comment by julienchastang** [comment]
Closing. Redid this based on forthcoming docker-compose.yml.

**Pull request closed without merging**
